server:
  port: 11000
spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    nacos:
      discovery:
        server-addr: kuro-nacos-server:8848
      config:
        server-addr: kuro-nacos-server:8848
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: ticket
          uri: lb://ticket
          predicates:
            - Path= /ticket/**
